### ISSUE TITLE
h:stack doesn't have size medium(m) defind

### ISSUE THREAD

**Issue by danielglazebrook** [almonk/pylon#2]
During testing I found that there is no value for medium (m) spacing on hstack

**Comment by almonk** [comment]
Well spotted – added now in https://github.com/almonk/pylon/commit/ef244df41cb332e5ee7d97e9738800702c5d9a7c

**Comment by danielglazebrook** [comment]
Medium size is also missing for list aswell i believe - https://github.com/almonk/pylon/blob/master/src/css/list.css
