### ISSUE TITLE
Conflict with web standards?

### ISSUE THREAD

**Issue by eavichay** [almonk/pylon#5]
Web standards imply that non-native tags should have at least one dash (i.e. `<x-list>`) and not `<list>`. This may be a problem in the future if browser vendors support new tags such as those introduced in pylon css framework.

WDYT?

**Comment by almonk** [comment]
I think this is totally valid. I plan to introduce a 'scoped' namespace as the default syntax for pylon in the future.

**Comment by eavichay** [comment]
scoping inside is a good practice IMO. Did you mean something like this?

```html
<div theme-pylon>
  <ul>
   ...
</div>
```
