### ISSUE TITLE
React compatibility

### ISSUE THREAD

**Issue by JuanSierra** [almonk/pylon#7]
How could be this library be compatible with React?, because of pylon uses custom tags

**Comment by almonk** [comment]
I don't think React specifically would play nicely with Pylon, but maybe someone more experienced with React could find a solution

**Comment by zaydek** [comment]
If you adapted the library to work with classes you could achieve this with _any_ codebase, not just React. In React you would just bind a classed `div` for example to get this to work.

If you’re interested, I’d recommending extending your library to work like this:

```css
hstack,
.hstack {
  ...
}
```

Then you can continue to prototype with it and extend it at the same time.
